export const LOAD_INITIAL_CONTACTS = 'LOAD_INITIAL_CONTACTS';
export const ADD_NEW_CONTACT = 'ADD_NEW_CONTACT';
export const SEARCH_CONTACTS = 'SEARCH_CONTACTS';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const NOTIFY_FAILURE = 'NOTIFY_FAILURE';
export const START_LOADING = 'START_LOADING';